// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OnPropertyChanger
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidOnPropertyChangerPackageString = "18fdf65a-815c-4b78-b950-895a8ca74070";
        public static Guid guidOnPropertyChangerPackage = new Guid(guidOnPropertyChangerPackageString);

        public const string guidOnPropertyChangerPackageCmdSetString = "c8593044-2e2a-460f-bb25-c87055eab71f";
        public static Guid guidOnPropertyChangerPackageCmdSet = new Guid(guidOnPropertyChangerPackageCmdSetString);

        public const string guidImagesString = "50c47ec9-6d13-4cca-af15-e5e22a746006";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int FixOnPropertyChangedCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}